import React, { useState, useEffect } from 'react';
import { Timer, Layers, Network, Zap, Brain, Wand2 } from 'lucide-react';
import { Button, Spinner } from './ui';
import PomodoroTimer from './PomodoroTimer';
import FlashcardDeck from './FlashcardDeck';
import KnowledgeMap from './KnowledgeMap';
import FeynmanAssistant from './FeynmanAssistant';
import { generateFlashcards as generateFlashcardsApi } from '../services/geminiService';

type ToolTab = 'timer' | 'flashcards' | 'map' | 'feynman';

interface StudyToolsPanelProps {
    notes: string;
    topic: string;
    isActive: boolean;
    tasks?: any[]; // Using any for simplicity here to avoid circular dependencies, or import StudyTask
    onTaskComplete?: (task: any) => void;
}

const StudyToolsPanel: React.FC<StudyToolsPanelProps> = ({ notes, topic, isActive, tasks = [], onTaskComplete }) => {
    const [activeTab, setActiveTab] = useState<ToolTab>('timer');
    const [flashcards, setFlashcards] = useState<{ front: string; back: string }[]>([]);
    const [isGeneratingCards, setIsGeneratingCards] = useState(false);
    const [mapData, setMapData] = useState<any[]>([]);

    // Initialize Map Data based on topic (Mock)
    useEffect(() => {
        if (topic) {
            // In a real app, this would be fetched or generated by AI
            setMapData([
                { name: topic, strength: 1.0 },
                { name: 'Prior Knowledge', strength: 0.8 },
                { name: 'Core Concepts', strength: 0.4 },
                { name: 'Advanced Theory', strength: 0.1 },
            ]);
        }
    }, [topic]);

    const handleGenerateFlashcards = async () => {
        if (!notes) return;
        setIsGeneratingCards(true);
        try {
            const result = await generateFlashcardsApi(notes);
            const cards = JSON.parse(result);
            setFlashcards(cards);
        } catch (error) {
            console.error("Failed to generate flashcards", error);
            // Ideally show toast
        } finally {
            setIsGeneratingCards(false);
        }
    };

    if (!isActive) return null;

    return (
        <div className="flex flex-col flex-1 overflow-hidden h-full bg-slate-900/40 relative">
            {/* Tool Selector */}
            <div className="flex gap-1 p-2 border-b border-white/5 bg-slate-900/60 backdrop-blur-md">
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setActiveTab('timer')}
                    className={`flex-1 text-xs ${activeTab === 'timer' ? 'bg-violet-600/20 text-violet-300' : 'text-slate-400'}`}
                >
                    <Timer size={14} className="mr-1.5" /> Focus
                </Button>
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setActiveTab('flashcards')}
                    className={`flex-1 text-xs ${activeTab === 'flashcards' ? 'bg-violet-600/20 text-violet-300' : 'text-slate-400'}`}
                >
                    <Layers size={14} className="mr-1.5" /> Cards
                </Button>
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setActiveTab('map')}
                    className={`flex-1 text-xs ${activeTab === 'map' ? 'bg-violet-600/20 text-violet-300' : 'text-slate-400'}`}
                >
                    <Network size={14} className="mr-1.5" /> Map
                </Button>
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setActiveTab('feynman')}
                    className={`flex-1 text-xs ${activeTab === 'feynman' ? 'bg-violet-600/20 text-violet-300' : 'text-slate-400'}`}
                >
                    <Brain size={14} className="mr-1.5" /> Feynman
                </Button>
            </div>

            {/* Content Area */}
            <div className="flex-1 overflow-y-auto p-4 scrollbar-thin scrollbar-thumb-slate-700">

                {/* TIMER TAB */}
                {activeTab === 'timer' && (
                    <div className="h-full flex flex-col items-center justify-center space-y-6">
                        <PomodoroTimer tasks={tasks} onTaskComplete={onTaskComplete} />
                        <div className="text-center space-y-2 max-w-xs">
                            <h4 className="text-sm font-medium text-slate-300 flex items-center justify-center gap-2">
                                <Brain size={16} className="text-violet-400" />
                                Study Technique
                            </h4>
                            <p className="text-xs text-slate-500 leading-relaxed">
                                The Pomodoro technique uses focused 25-minute work intervals separated by short breaks to maximize concentration and prevent burnout.
                            </p>
                        </div>
                    </div>
                )}

                {/* FLASHCARDS TAB */}
                {activeTab === 'flashcards' && (
                    <div className="h-full flex flex-col">
                        {flashcards.length === 0 ? (
                            <div className="flex-1 flex flex-col items-center justify-center text-center space-y-4">
                                <div className="w-16 h-16 rounded-full bg-slate-800 flex items-center justify-center ring-1 ring-white/10">
                                    <Layers size={32} className="text-slate-500" />
                                </div>
                                <div>
                                    <h3 className="text-slate-200 font-medium mb-1">No Flashcards Yet</h3>
                                    <p className="text-xs text-slate-500 max-w-[200px] mx-auto">Generate cards from your shared notes to test your knowledge.</p>
                                </div>
                                <Button
                                    onClick={handleGenerateFlashcards}
                                    disabled={!notes || isGeneratingCards}
                                    className="w-full max-w-xs bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 border-none shadow-lg shadow-violet-900/20"
                                >
                                    {isGeneratingCards ? (
                                        <><Spinner size="sm" className="mr-2" /> Creating Deck...</>
                                    ) : (
                                        <><Wand2 size={16} className="mr-2" /> Generate from Notes</>
                                    )}
                                </Button>
                                {!notes && <p className="text-[10px] text-red-400/80">Upload notes in the 'Notes' tab first.</p>}
                            </div>
                        ) : (
                            <div className="space-y-6">
                                <div className="flex justify-between items-center mb-2">
                                    <h3 className="text-sm font-medium text-slate-400 uppercase tracking-wider">Active Deck</h3>
                                    <Button
                                        variant="ghost"
                                        size="sm"
                                        onClick={handleGenerateFlashcards}
                                        className="h-6 text-[10px] text-violet-400 hover:text-violet-300 px-2"
                                        disabled={isGeneratingCards}
                                    >
                                        <Wand2 size={10} className="mr-1" /> Regenerate
                                    </Button>
                                </div>
                                <FlashcardDeck cards={flashcards} />
                            </div>
                        )}
                    </div>
                )}

                {/* MAP TAB */}
                {activeTab === 'map' && (
                    <div className="h-full flex flex-col">
                        <div className="mb-4">
                            <h3 className="text-sm font-medium text-slate-200 mb-1 flex items-center gap-2">
                                <Network size={16} className="text-emerald-400" /> Topic Topology
                            </h3>
                            <p className="text-xs text-slate-500">Visual mapping of current study concepts.</p>
                        </div>
                        <div className="flex-1 flex bg-slate-900/50 rounded-xl overflow-hidden ring-1 ring-white/5">
                            <KnowledgeMap topics={mapData} />
                        </div>
                    </div>
                )}

                {/* FEYNMAN TAB */}
                {activeTab === 'feynman' && (
                    <div className="h-full flex flex-col">
                        <FeynmanAssistant topic={topic || 'this concept'} notes={notes} />
                        <div className="mt-4 p-3 bg-violet-600/10 rounded-xl border border-violet-500/20">
                            <p className="text-[10px] text-slate-400 leading-relaxed italic">
                                "If you want to master something, teach it. The Feynman Technique identifies gaps in your knowledge by challenging you to explain complex ideas in simple terms."
                            </p>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default StudyToolsPanel;
