import React, { useState, useEffect, useRef } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { getCourses, addCourse } from '../services/courseService';
import { getNotes, addTextNote, uploadNoteFile, deleteNote, getFlashcards, addFlashcards, updateFlashcard, updateNoteContent, getQuizzes, savePersonalQuiz, updateQuizScore } from '../services/notesService';
import { getStudyPlan, saveStudyPlan, updateTaskCompletion } from '../services/studyPlanService';
import { type Note, type Course, type Flashcard as FlashcardType, type StudyPlan, type StudyTask, type PersonalQuiz } from '../types';
import { PageHeader, Button, Input, Textarea, Select, Modal, Spinner } from '../components/ui';
import { PlusCircle, Trash2, Upload, FileText, BookOpen, Layers, X, Brain, Edit, Save, ArrowLeft, Download, Eye, EyeOff, Calendar, Target, CheckCircle2, Circle, Users } from 'lucide-react';
import { generateFlashcards, extractTextFromFile, generateStudyPlan, generateQuizSet } from '../services/geminiService';
import { useNavigate, useLocation } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
import Flashcard from '../components/Flashcard';


// Helper function
const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      if (!result || !result.includes(',')) {
        return reject(new Error("Invalid file data for base64 conversion"));
      }
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(file);
  });
};


const StudyPlanView: React.FC<{
  courseId: string;
  notes: Note[];
  studyPlan: StudyPlan | null;
  onPlanSaved: (plan: StudyPlan) => void;
}> = ({ courseId, notes, studyPlan, onPlanSaved }) => {
  const [goal, setGoal] = useState('');
  const [duration, setDuration] = useState('7');
  const [isGenerating, setIsGenerating] = useState(false);

  const { language } = useLanguage();
  const handleGenerate = async () => {
    if (!goal || !courseId) return;

    setIsGenerating(true);
    try {
      const notesContext = notes
        .map(n => n.content || '')
        .filter(c => c.length > 0)
        .join('\n\n');

      const planJson = await generateStudyPlan(goal, parseInt(duration), notesContext, language);
      const parsedData = JSON.parse(planJson);

      // Handle both cases: a direct array or an object with a 'days' key
      const days = Array.isArray(parsedData) ? parsedData : (parsedData.days || []);

      if (days.length === 0) {
        throw new Error("No study days generated by AI.");
      }

      const newPlan = await saveStudyPlan({
        courseId,
        goal,
        durationDays: parseInt(duration),
        startDate: Date.now(),
        days: days.map((d: any) => ({
          ...d,
          tasks: (d.tasks || []).map((t: any) => ({
            ...t,
            id: `task_${Math.random().toString(36).substr(2, 9)}`,
            completed: false
          }))
        }))
      });

      if (newPlan) {
        onPlanSaved(newPlan);
        alert("Personalized study plan created!");
      }
    } catch (error) {
      console.error("Failed to generate study plan:", error);
      alert("Failed to generate study plan. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleTask = async (dayIndex: number, taskId: string, currentStatus: boolean) => {
    const updatedPlan = await updateTaskCompletion(courseId, dayIndex, taskId, !currentStatus);
    if (updatedPlan) {
      onPlanSaved(updatedPlan);
    }
  };

  const getTaskIcon = (type: string) => {
    switch (type) {
      case 'note': return <FileText size={16} className="text-sky-400" />;
      case 'quiz': return <Brain size={16} className="text-emerald-400" />;
      case 'study-room': return <Users size={16} className="text-violet-400" />;
      default: return <Target size={16} className="text-slate-400" />;
    }
  };

  if (isGenerating) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-4">
        <Spinner size="lg" />
        <h3 className="text-xl font-bold text-white">AI is crafting your study journey...</h3>
        <p className="text-slate-400 max-w-md">We're analyzing your notes and goal to build a path tailored specifically for you.</p>
      </div>
    );
  }

  if (!studyPlan) {
    return (
      <div className="flex-1 w-full overflow-y-auto bg-slate-900/40 p-4 min-h-0">
        <div className="min-h-full flex flex-col items-center justify-center p-4">
          <div className="bg-slate-800/80 p-8 rounded-2xl max-w-xl w-full ring-1 ring-slate-700 shadow-xl my-auto">
            <Calendar className="w-12 h-12 text-violet-400 mx-auto mb-4" />
            <h3 className="text-2xl font-bold text-white mb-2">Create Your AI Study Plan</h3>
            <p className="text-slate-400 mb-8">
              Tell the AI your goal (e.g., "Ace the Calculus midterm"), set your timeframe,
              and we'll generate a day-by-day plan linked to your notes.
            </p>

            <div className="space-y-4 text-left">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Academic Goal</label>
                <Input
                  placeholder="e.g., Master organic chemistry mechanisms"
                  value={goal}
                  onChange={e => setGoal(e.target.value)}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Timeframe (Days)</label>
                <Select value={duration} onChange={e => setDuration(e.target.value)}>
                  {[3, 5, 7, 10, 14, 21, 30].map(d => (
                    <option key={d} value={d}>{d} Days</option>
                  ))}
                </Select>
              </div>
            </div>

            <Button onClick={handleGenerate} className="w-full mt-8" disabled={!goal}>
              Generate Personalized Plan
            </Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-slate-900/40 min-h-0">
      <div className="flex justify-between items-end bg-slate-800/80 p-6 rounded-xl ring-1 ring-slate-700">
        <div>
          <h3 className="text-sm font-semibold text-violet-400 uppercase tracking-wider mb-1">Current Focus</h3>
          <h2 className="text-2xl font-bold text-white">{studyPlan.goal}</h2>
          <p className="text-slate-400 mt-1">Starting {new Date(studyPlan.startDate).toLocaleDateString()}</p>
        </div>
        <Button variant="ghost" className="text-slate-400 hover:text-white text-sm" onClick={() => {
          if (confirm("Create a new plan? This will replace your current one.")) {
            onPlanSaved(null as any);
          }
        }}>
          New Plan
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {studyPlan.days.map((day, idx) => {
          const isCompleted = day.tasks.every(t => t.completed);
          return (
            <div key={idx} className={`bg-slate-800/60 p-5 rounded-xl ring-1 transition-all ${isCompleted ? 'ring-emerald-500/30 opacity-80' : 'ring-slate-700 hover:ring-slate-600'}`}>
              <div className="flex justify-between items-center mb-4">
                <h4 className="font-bold text-slate-200">Day {day.day}</h4>
                {isCompleted && <CheckCircle2 className="text-emerald-400" size={18} />}
              </div>

              <div className="space-y-3">
                {day.tasks.map((task) => (
                  <div
                    key={task.id}
                    onClick={() => toggleTask(idx, (task._id || task.id)!, task.completed)}
                    className={`group cursor-pointer p-3 rounded-lg border transition-all ${task.completed
                      ? 'bg-emerald-900/10 border-emerald-500/20 text-slate-500'
                      : 'bg-slate-700/50 border-transparent hover:border-violet-500/50 text-slate-200'
                      }`}
                  >
                    <div className="flex items-start gap-3">
                      <div className="mt-1 flex-shrink-0">
                        {task.completed ? <CheckCircle2 size={16} className="text-emerald-400" /> : <Circle size={16} className="text-slate-500 group-hover:text-violet-400" />}
                      </div>
                      <div className="flex-1 overflow-hidden">
                        <div className="flex items-center gap-2 mb-0.5">
                          {getTaskIcon(task.type)}
                          <p className={`font-semibold text-sm truncate ${task.completed ? 'line-through' : ''}`}>{task.title}</p>
                        </div>
                        <p className="text-xs text-slate-400 line-clamp-2">{task.description}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

const Notes: React.FC = () => {

  const navigate = useNavigate();
  const { user } = useAuth();

  // --- State Management ---
  const [courses, setCourses] = useState<Course[]>([]);
  const [selectedCourse, setSelectedCourse] = useState<string>('');
  const [notes, setNotes] = useState<Note[]>([]);
  const { language } = useLanguage();
  const [activeNote, setActiveNote] = useState<Note | null>(null);
  const [isEditingNote, setIsEditingNote] = useState(false);
  const [editedContent, setEditedContent] = useState('');

  const [flashcards, setFlashcards] = useState<FlashcardType[]>([]);
  const [quizzes, setQuizzes] = useState<PersonalQuiz[]>([]); // New state
  const [studyPlan, setStudyPlan] = useState<StudyPlan | null>(null);

  const [activeTab, setActiveTab] = useState<'notes' | 'flashcards' | 'plan' | 'quiz'>('notes'); // Added 'quiz'
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false); // Loading state for note-based generation
  const [isQuizGenerating, setIsQuizGenerating] = useState(false); // New loading state for quiz
  const [isFileGenerating, setIsFileGenerating] = useState(false); // Loading state for file-based generation
  const [isSingleGenerating, setIsSingleGenerating] = useState<string | null>(null); // Track which note ID is generating

  const location = useLocation();

  // Handle deep linking from Dashboard
  useEffect(() => {
    if (location.state?.activeTab) {
      setActiveTab(location.state.activeTab);
    }
    if (location.state?.courseId) {
      setSelectedCourse(location.state.courseId);
    }
  }, [location]);


  // --- Data Fetching Effects ---
  useEffect(() => {
    if (user) {
      console.log("[Notes] Fetching courses for user:", user);
      getCourses()
        .then(fetchedCourses => {
          console.log(`[Notes] Successfully fetched ${fetchedCourses.length} courses`);
          setCourses(fetchedCourses);
        })
        .catch(error => {
          console.error("[Notes] Error fetching courses:", error);
          // Don't show alert here as it might be annoying on every page load
          // User will see error when trying to add a course instead
        });
    }
  }, [user]);

  useEffect(() => {
    if (selectedCourse) {
      setActiveNote(null);
      setIsEditingNote(false);
      getNotes(selectedCourse).then(setNotes);
      getFlashcards(selectedCourse).then(setFlashcards);
      getQuizzes(selectedCourse).then(setQuizzes);
      getStudyPlan(selectedCourse).then(setStudyPlan);
    } else {
      setNotes([]);
      setFlashcards([]);
      setQuizzes([]);
      setStudyPlan(null);
      setActiveNote(null);
    }

  }, [selectedCourse]);

  // --- Handlers ---
  const handleAddCourse = async () => {
    const courseName = prompt("Enter the name of the new course:");
    if (!courseName || courseName.trim() === '') {
      console.log("[Notes] Course creation cancelled - no name provided");
      return;
    }

    console.log(`[Notes] Attempting to add course: "${courseName}"`);

    try {
      const newCourse = await addCourse(courseName.trim());

      if (newCourse) {
        console.log(`[Notes] Successfully added course:`, newCourse);
        setCourses(prev => [...prev, newCourse]);
        setSelectedCourse(newCourse.id);
        alert(`✅ Course "${courseName}" added successfully!`);
      } else {
        console.error("[Notes] addCourse returned null");
        alert("❌ Failed to add course. Please check your Firebase configuration.");
      }
    } catch (error) {
      console.error("[Notes] Error adding course:", error);
      const errorMessage = error instanceof Error ? error.message : String(error);

      if (errorMessage.includes("Database not initialized")) {
        alert("❌ Database connection failed. Please check your backend server.");
      } else if (errorMessage.includes("insufficient permissions")) {
        alert("❌ Permission denied. You might need to log in again.");
      } else {
        alert(`❌ Failed to add course: ${errorMessage}`);
      }
    }
  };

  const reloadNotes = () => {
    if (selectedCourse) {
      getNotes(selectedCourse).then(setNotes);
    }
  };
  const reloadFlashcards = () => {
    if (selectedCourse) {
      getFlashcards(selectedCourse).then(setFlashcards);
    }
  };

  const handleSelectNote = (note: Note) => {
    setActiveNote(note);
    setEditedContent(note.content || '');
    setIsEditingNote(false);
  };

  // --- FIX: Updated function signature (no 'e' or 'noteId') ---
  const handleDeleteNote = async (noteToDelete: Note) => {
    if (!selectedCourse || !window.confirm("Are you sure you want to delete this note?")) return;

    if (noteToDelete) {
      await deleteNote(selectedCourse, noteToDelete);
      reloadNotes();
      if (activeNote?.id === noteToDelete.id) {
        setActiveNote(null);
      }
    }
  };
  // --- END FIX ---

  const handleSaveNoteEdit = async () => {
    if (!activeNote || !selectedCourse) return;

    try {
      await updateNoteContent(selectedCourse, activeNote.id, editedContent);
      console.log("Saved note:", activeNote.id, "with content:", editedContent);
      setActiveNote(prev => prev ? { ...prev, content: editedContent } : null);
      setNotes(prev => prev.map(n => n.id === activeNote.id ? { ...n, content: editedContent } : n));
      setIsEditingNote(false);
    } catch (error) {
      console.error("Failed to save note edit:", error);
      alert("Failed to save your changes. Please try again.");
    }
  };

  const handleGenerateFromNotes = async () => {
    if (!selectedCourse || notes.length === 0 || isGenerating || isFileGenerating || isSingleGenerating) return;

    setIsGenerating(true);
    const validNotesContent = notes
      .filter(n => n.content && n.content !== "[Text extraction pending or failed]")
      .map(n => n.content);

    if (validNotesContent.length === 0) {
      alert("No text content found in your notes to generate flashcards from.");
      setIsGenerating(false);
      return;
    }
    const content = validNotesContent.join('\n\n');

    try {
      console.log("Generating flashcards from combined notes content length:", content.length);
      const flashcardsJson = await generateFlashcards(content, language);
      const newFlashcards = JSON.parse(flashcardsJson).map((f: any) => ({
        ...f,
        id: `mock_flashcard_${Date.now()}_${Math.random()}`,
        bucket: 1,
        lastReview: Date.now()
      }));
      await addFlashcards(selectedCourse, newFlashcards);
      reloadFlashcards();
      alert(`Successfully generated ${newFlashcards.length} flashcards from notes!`);
    } catch (error) {
      console.error("Failed to generate or parse flashcards from notes:", error);
      alert("Failed to generate flashcards from notes. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGenerateFromFile = async (file: File | null) => {
    if (!file || !selectedCourse || isGenerating || isFileGenerating || isSingleGenerating) return;

    setIsFileGenerating(true);
    let extractedContent = '';
    try {
      const base64Data = await fileToBase64(file);

      let mimeType = file.type;
      if (!mimeType) {
        const extension = file.name.split('.').pop()?.toLowerCase();
        const mimeMap: { [key: string]: string } = {
          'pdf': 'application/pdf',
          'txt': 'text/plain',
          'md': 'text/plain',
          'png': 'image/png',
          'jpg': 'image/jpeg',
          'jpeg': 'image/jpeg',
          'pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
          'ppt': 'application/vnd.ms-powerpoint'
        };
        mimeType = mimeMap[extension || ''] || 'application/octet-stream';
      }

      extractedContent = await extractTextFromFile(base64Data, mimeType);
      console.log(`Extracted ${extractedContent.length} characters from ${file.name}`);

      if (!extractedContent || extractedContent.trim().length === 0) {
        alert(`Could not extract any text from ${file.name}. Flashcard generation cancelled.`);
        setIsFileGenerating(false);
        return;
      }

      console.log(`Generating flashcards from extracted text (length: ${extractedContent.length})`);
      const flashcardsJson = await generateFlashcards(extractedContent, language);
      const newFlashcards = JSON.parse(flashcardsJson).map((f: any) => ({
        ...f,
        id: `mock_flashcard_${Date.now()}_${Math.random()}`,
        bucket: 1,
        lastReview: Date.now()
      }));

      await addFlashcards(selectedCourse, newFlashcards);
      reloadFlashcards();
      alert(`Successfully generated ${newFlashcards.length} flashcards from the file ${file.name}!`);

    } catch (error) {
      console.error(`Failed process file ${file.name} for flashcards:`, error);
      alert(`Failed to generate flashcards from the file ${file.name}. Please try again.`);
    } finally {
      setIsFileGenerating(false);
    }
  };

  // --- FIX: Updated function signature (no 'e') ---
  const handleGenerateSingleNoteFlashcards = async (note: Note) => {
    if (!note.content || note.content === "[Text extraction pending or failed]" || !selectedCourse || isGenerating || isFileGenerating || isSingleGenerating) {
      alert("This note doesn't have any text content to generate flashcards from.");
      return;
    }

    setIsSingleGenerating(note.id);
    try {
      console.log(`Generating flashcards from single note '${note.title}' (length: ${note.content.length})`);
      const flashcardsJson = await generateFlashcards(note.content, language);
      const newFlashcards = JSON.parse(flashcardsJson).map((f: any) => ({
        ...f,
        id: `mock_flashcard_${Date.now()}_${Math.random()}`,
        bucket: 1,
        lastReview: Date.now()
      }));

      await addFlashcards(selectedCourse, newFlashcards);
      reloadFlashcards();
      alert(`Successfully generated ${newFlashcards.length} flashcards from the note '${note.title}'!`);
      setActiveTab('flashcards'); // Switch to flashcards tab after generation

    } catch (error) {
      console.error(`Failed to generate flashcards from note ${note.id}:`, error);
      alert(`Failed to generate flashcards from the note '${note.title}'. Please try again.`);
    } finally {
      setIsSingleGenerating(null);
    }
  };
  // --- END FIX ---

  const handleGenerateQuiz = async () => {
    if (!selectedCourse || notes.length === 0 || isQuizGenerating) return;

    setIsQuizGenerating(true);
    const validNotesContent = notes
      .filter(n => n.content && n.content !== "[Text extraction pending or failed]")
      .map(n => n.content);

    if (validNotesContent.length === 0) {
      alert("No text content found in your notes to generate a quiz from.");
      setIsQuizGenerating(false);
      return;
    }
    const content = validNotesContent.join('\n\n');

    try {
      console.log("Generating quiz from notes...");
      const quizJson = await generateQuizSet(content, 5, language); // Default 5 questions
      const questionSet = JSON.parse(quizJson);

      const newQuiz: PersonalQuiz = {
        id: `quiz_${Date.now()}`,
        questions: questionSet,
        score: 0,
        completed: false,
        dateTaken: Date.now()
      };

      // Save to backend
      await savePersonalQuiz(selectedCourse, newQuiz);
      setQuizzes(prev => [newQuiz, ...prev]);
      setActiveTab('quiz'); // Switch to quiz tab
      alert(`Successfully generated a quiz with ${questionSet.length} questions!`);

    } catch (error) {
      console.error("Failed to generate quiz:", error);
      alert("Failed to generate quiz. Please try again.");
    } finally {
      setIsQuizGenerating(false);
    }
  };

  const onUpdateQuizScore = (quizId: string, score: number) => {
    setQuizzes(prev => prev.map(q => q.id === quizId ? { ...q, score, completed: true } : q));
    updateQuizScore(selectedCourse, quizId, score);
  };


  // --- FIX: This is the main component's return, now INSIDE the component ---
  return (
    <div className="space-y-6 h-full flex flex-col">
      <PageHeader title="Notes & Resources" subtitle="Manage your notes, files, and flashcards for each course." />

      {/* --- Course Selector --- */}
      <div className="flex items-center gap-2">
        <BookOpen className="w-6 h-6 mr-2 text-violet-400" />
        <Select
          id="course-select-notes"
          name="courseId"
          value={selectedCourse}
          onChange={e => setSelectedCourse(e.target.value)}
          className="w-full md:w-1/3"
        >
          <option value="">Select a Course</option>
          {courses.map(course =>
            <option key={course.id} value={course.id}>{course.name}</option>
          )}
        </Select>
        <Button onClick={handleAddCourse} className="p-2.5"><PlusCircle size={16} /></Button>
      </div>

      {selectedCourse ? (
        <div className="flex-1 flex flex-col bg-slate-800/50 rounded-xl ring-1 ring-slate-700 overflow-hidden">
          {/* --- Tabs --- */}
          <div className="flex border-b border-slate-700">
            <TabButton
              icon={BookOpen}
              label="My Notes"
              isActive={activeTab === 'notes'}
              onClick={() => setActiveTab('notes')}
            />
            <TabButton
              icon={Layers}
              label={`Flashcards(${flashcards.length})`}
              isActive={activeTab === 'flashcards'}
              onClick={() => setActiveTab('flashcards')}
            />
            <TabButton
              icon={Brain}
              label="Quiz"
              isActive={activeTab === 'quiz'}
              onClick={() => setActiveTab('quiz')}
            />
            <TabButton
              icon={Calendar}
              label="Study Plan"
              isActive={activeTab === 'plan'}
              onClick={() => setActiveTab('plan')}
            />
          </div>


          {/* --- Content Area --- */}
          {activeTab === 'notes' && (
            <NotesView
              notes={notes}
              activeNote={activeNote}
              isEditingNote={isEditingNote}
              editedContent={editedContent}
              isSingleGenerating={isSingleGenerating} // Pass loading state down
              onSelectNote={handleSelectNote}
              onDeleteNote={handleDeleteNote} // Pass corrected handler
              onSaveEdit={handleSaveNoteEdit}
              onEditClick={() => setIsEditingNote(true)}
              onContentChange={setEditedContent}
              onAddNoteClick={() => setIsModalOpen(true)}
              onGenerateSingleNoteFlashcards={handleGenerateSingleNoteFlashcards} // Pass corrected handler
            />
          )}

          {activeTab === 'flashcards' && (
            <FlashcardsView
              flashcards={flashcards}
              onGenerateFromNotes={handleGenerateFromNotes}
              onGenerateFromFile={handleGenerateFromFile}
              isGenerating={isGenerating}
              isFileGenerating={isFileGenerating}
              courseId={selectedCourse}
              onUpdateCard={async (card, correct) => {
                const newBucket = correct ? Math.min(card.bucket + 1, 4) : 1;
                await updateFlashcard(selectedCourse, card.id, { bucket: newBucket, lastReview: Date.now() });
                reloadFlashcards();
              }}
            />
          )}

          {activeTab === 'quiz' && (
            <QuizView
              quizzes={quizzes}
              onGenerateQuiz={handleGenerateQuiz}
              isGenerating={isQuizGenerating}
              onUpdateScore={onUpdateQuizScore}
            />
          )}

          {activeTab === 'plan' && (
            <StudyPlanView
              courseId={selectedCourse}
              notes={notes}
              studyPlan={studyPlan}
              onPlanSaved={setStudyPlan}
            />
          )}
        </div>

      ) : (
        <div className="flex-1 flex items-center justify-center bg-slate-800/50 rounded-xl ring-1 ring-slate-700">
          <p className="text-slate-400">Please select a course to view your notes.</p>
        </div>
      )}

      {/* --- Add Note Modal --- */}
      <AddNoteModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        courseId={selectedCourse}
        onNoteAdded={reloadNotes}
      />
    </div>
  );
  // --- END FIX ---
};

// --- TabButton Component ---
const TabButton: React.FC<{ icon: React.ElementType, label: string, isActive: boolean, onClick: () => void }> = ({ icon: Icon, label, isActive, onClick }) => (
  <button
    onClick={onClick}
    className={`flex items-center justify-center gap-2 px-4 py-3 font-semibold transition-colors ${isActive
      ? 'text-violet-400 border-b-2 border-violet-400'
      : 'text-slate-400 hover:text-white'
      }`}
  >
    <Icon size={18} /> {label}
  </button>
);

// --- FIX: Replaced entire NotesView component with the correct version ---
// --- NotesView Sub-Component ---
const NotesView: React.FC<{
  notes: Note[];
  activeNote: Note | null;
  isEditingNote: boolean;
  editedContent: string;
  isSingleGenerating: string | null;
  onSelectNote: (note: Note) => void;
  onDeleteNote: (note: Note) => void;
  onSaveEdit: (note: Note) => void;
  onEditClick: () => void;
  onContentChange: (content: string) => void;
  onAddNoteClick: () => void;
  onGenerateSingleNoteFlashcards: (note: Note) => void;
}> = ({
  notes,
  activeNote,
  isEditingNote,
  editedContent,
  isSingleGenerating,
  onSelectNote,
  onDeleteNote,
  onSaveEdit,
  onEditClick,
  onContentChange,
  onAddNoteClick,
  onGenerateSingleNoteFlashcards
}) => {
    const navigate = useNavigate();

    const handleDownloadFile = (note: Note) => {
      if ((note.type === 'file' || note.fileUrl) && note.fileUrl) { // Check for fileUrl
        const link = document.createElement('a');
        link.href = note.fileUrl;
        link.download = note.fileName || (note.title.endsWith(note.fileExtension || '') ? note.title : `${note.title}.${note.fileExtension || 'txt'} `);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      } else if (note.type === 'text') {
        const blob = new Blob([note.content], { type: 'text/plain;charset=utf-8' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `${note.title}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }
    };

    return (
      <div className="flex flex-1 overflow-hidden">
        {/* --- Notes List --- */}
        <div className="w-1/3 border-r border-slate-700 flex flex-col">
          <div className="p-6 border-b border-slate-700">
            <Button onClick={onAddNoteClick} className="w-full">
              <PlusCircle size={16} className="mr-2" /> Add Note / File
            </Button>
          </div>
          <div className="flex-1 overflow-y-auto">
            {notes.length === 0 && (
              <p className="text-center text-slate-400 p-8 text-sm">No notes yet.</p>
            )}
            {notes.map(note => {
              const isGeneratingThis = isSingleGenerating === note.id;
              const hasContent = note.content && note.content !== "[Text extraction pending or failed]";
              return (
                <div // Changed from <button> to <div>
                  key={note.id}
                  onClick={() => onSelectNote(note)}
                  className={`w-full text-left p-4 border-b border-slate-700 transition-colors group flex justify-between items-start cursor-pointer ${activeNote?.id === note.id ? 'bg-slate-700' : 'hover:bg-slate-700/50'}`}
                  role="button" // Added accessibility role
                  tabIndex={0} // Make it focusable
                  onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && onSelectNote(note)} // Allow keyboard activation
                >
                  {/* Note content remains the same */}
                  <div className="flex items-center gap-2 overflow-hidden">
                    {note.type === 'text' || !note.fileUrl ? <FileText size={14} className="mr-2 flex-shrink-0 text-slate-400" /> : <Upload size={14} className="mr-2 flex-shrink-0 text-sky-400" />}
                    <h4 className="font-semibold text-slate-100 truncate">
                      {note.title}
                    </h4>
                  </div>
                  {/* Action Buttons remain inside the div */}
                  <div className="flex-shrink-0 flex items-center gap-1 ml-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    {hasContent && (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="p-1 h-auto hover:bg-violet-500/30"
                        title="Generate Flashcards from this note"
                        onClick={(e) => {
                          e.stopPropagation();
                          onGenerateSingleNoteFlashcards(note);
                        }}
                        disabled={isGeneratingThis || !!isSingleGenerating}
                      >
                        {isGeneratingThis ? <Spinner size="sm" /> : <Layers size={14} className="text-violet-400" />}
                      </Button>
                    )}
                    <Button // The inner button (_c2) is now valid as it's inside a div
                      variant="ghost"
                      size="sm"
                      className="p-1 h-auto hover:bg-red-500/30"
                      title="Delete Note"
                      onClick={(e) => {
                        e.stopPropagation();
                        onDeleteNote(note);
                      }}
                      disabled={isGeneratingThis || !!isSingleGenerating}
                    >
                      <Trash2 size={14} className="text-red-400" />
                    </Button>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* --- Active Note Panel --- */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {activeNote ? (
            <div className="flex-1 flex flex-col h-full overflow-y-auto">
              {/* --- Toolbar --- */}
              <div className="flex justify-between items-center p-4 border-b border-slate-700 bg-slate-800 sticky top-0 z-10">
                <h3 className="text-lg font-semibold text-white truncate">{activeNote.title}</h3>
                <div className="flex items-center gap-2 flex-shrink-0">

                  {/* --- Generate Flashcards Button (as requested) --- */}
                  <Button
                    onClick={() => onGenerateSingleNoteFlashcards(activeNote)}
                    disabled={isSingleGenerating === activeNote.id || (activeNote.type === 'text' && !activeNote.content) || (!activeNote.content)}
                    className="p-2 text-slate-400 hover:text-white transition-colors"
                    aria-label="Generate Flashcards"
                    title="Generate Flashcards"
                  >
                    {isSingleGenerating === activeNote.id ? <Spinner size={16} /> : <Layers size={16} />}
                  </Button>

                  {/* --- Study with AI Button --- */}
                  {activeNote.content && activeNote.content !== "[Text extraction pending or failed]" && (
                    <Button
                      onClick={() => navigate('/tutor', { state: { noteContent: activeNote.content } })}
                      className="p-2 text-slate-400 hover:text-white transition-colors"
                      aria-label="Study with AI"
                      title="Study with AI">
                      <Brain size={16} />
                    </Button>
                  )}

                  {/* --- Download Button --- */}
                  <Button
                    onClick={() => handleDownloadFile(activeNote)}
                    className="p-2 text-slate-400 hover:text-white transition-colors"
                    aria-label="Download note"
                    title="Download"
                  >
                    <Download size={16} />
                  </Button>

                  {/* --- Edit/Save Buttons --- */}
                  {activeNote.type === 'text' && (
                    isEditingNote ? (
                      <Button onClick={() => onSaveEdit(activeNote)} className="px-3 py-1.5 text-xs">
                        <Save size={14} className="mr-1" /> Save
                      </Button>
                    ) : (
                      <Button onClick={onEditClick} className="p-2 text-slate-400 hover:text-white transition-colors" aria-label="Edit note" title="Edit">
                        <Edit size={16} />
                      </Button>
                    )
                  )}

                  {/* --- Delete Button --- */}
                  <Button onClick={() => onDeleteNote(activeNote)} className="p-2 text-red-500 hover:text-red-400 transition-colors" aria-label="Delete note" title="Delete">
                    <Trash2 size={16} />
                  </Button>

                </div>
              </div>

              {/* --- Content Display --- */}
              {isEditingNote && activeNote.type === 'text' ? (
                <Textarea
                  id="note-edit-textarea"
                  name="noteContent"
                  value={editedContent}
                  onChange={(e) => onContentChange(e.target.value)}
                  className="flex-1 w-full h-full p-4 bg-slate-800 border-none focus:ring-0 text-base"
                  placeholder="Start writing your note..."
                />
              ) : (
                <div className="p-4">
                  {activeNote.type === 'text' && (
                    <div className="prose prose-invert max-w-none whitespace-pre-wrap">{activeNote.content || <p className="text-slate-400">This note is empty. Click 'Edit' to start writing.</p>}</div>
                  )}
                  {(activeNote.type === 'file' || activeNote.fileUrl) && activeNote.type !== 'text' && (
                    <div className="p-4 bg-slate-700/50 rounded-lg text-center">
                      <p className="text-slate-300">File Note: <span className="font-semibold text-white">{activeNote.fileName || activeNote.title}</span></p>
                      <p className="text-sm text-slate-400 mt-2">This is a file resource. You can download it or generate flashcards from its content using the buttons above.</p>
                      {activeNote.content === "[Text extraction pending or failed]" && (
                        <p className="text-amber-400 text-sm mt-2">Could not automatically extract text from this file.</p>
                      )}
                    </div>
                  )}
                </div>
              )}
            </div>
          ) : (
            <div className="flex-1 flex items-center justify-center">
              <p className="text-slate-500"><ArrowLeft size={16} className="inline mr-2" /> Select a note to view or edit</p>
            </div>
          )}
        </div>
      </div>
    );
  };
// --- END REPLACEMENT ---


// --- AddNoteModal Sub-Component (MODIFIED) ---
const AddNoteModal: React.FC<{ isOpen: boolean, onClose: () => void, courseId: string, onNoteAdded: () => void }> = ({
  isOpen, onClose, courseId, onNoteAdded
}) => {

  const [title, setTitle] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [noteType, setNoteType] = useState<'text' | 'file'>('file');
  const [content, setContent] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // Validation
    if (!courseId) return;
    if (noteType === 'file' && !file) {
      alert("Please select a file to upload");
      return;
    }
    if (noteType === 'text' && !content) {
      alert("Please enter some content for the note");
      return;
    }

    setIsSubmitting(true);
    try {
      if (noteType === 'file' && file) {
        await uploadNoteFile(courseId, title || file.name, file);
      } else if (noteType === 'text') {
        const noteTitle = title || "Untitled Note";
        await addTextNote(courseId, noteTitle, content);
      }
      onNoteAdded(); // Refresh the notes list
    } catch (error) {
      console.error("Failed to add note:", error);
      alert("Failed to add the note. Please try again.");
    } finally {
      setIsSubmitting(false);
      // Reset local state *before* closing to avoid flicker
      setTitle('');
      setContent('');
      setFile(null);
      setNoteType('file');
      onClose();
    }
  };

  // Reset internal state when the modal is closed externally
  useEffect(() => {
    if (!isOpen) {
      setTitle('');
      setContent('');
      setFile(null);
      setNoteType('file');
      setIsSubmitting(false);
    }
  }, [isOpen]);

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Add New Resource">
      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="flex justify-center bg-slate-700/50 rounded-lg p-1">
          <Button type="button" onClick={() => setNoteType('text')} className={`w-1/2 rounded-md ${noteType === 'text' ? 'bg-violet-600 shadow-md' : 'bg-transparent text-slate-400 hover:text-white hover:bg-slate-600/50'}`}>
            <FileText size={16} className="mr-2" /> Text Note
          </Button>
          <Button type="button" onClick={() => setNoteType('file')} className={`w-1/2 rounded-md ${noteType === 'file' ? 'bg-violet-600 shadow-md' : 'bg-transparent text-slate-400 hover:text-white hover:bg-slate-600/50'}`}>
            <Upload size={16} className="mr-2" /> Upload File
          </Button>
        </div>

        <Input
          id="add-note-title"
          name="noteTitle"
          placeholder="Title (Optional - uses filename if blank)" // Changed placeholder
          value={title}
          onChange={e => setTitle(e.target.value)}
        // required // Title is now optional
        />

        {noteType === 'text' && (
          <Textarea
            placeholder="Write your note or doubt here..."
            value={content}
            onChange={e => setContent(e.target.value)}
            rows={8}
            className="bg-slate-900/50 border-white/5 resize-none focus:ring-violet-500/50"
          />
        )}

        {noteType === 'file' && (
          <div className="flex items-center justify-center w-full">
            <label htmlFor="modal-file-upload" className="flex flex-col items-center justify-center w-full h-32 border-2 border-slate-600 border-dashed rounded-lg cursor-pointer bg-slate-700/50 hover:bg-slate-700/50 hover:border-violet-500 transition-all group">
              <div className="flex flex-col items-center justify-center pt-5 pb-6">
                <Upload size={24} className="text-slate-400 mb-2 group-hover:text-violet-400 transition-colors" />
                <p className="mb-2 text-sm text-slate-400 text-center px-2">
                  {file ? <span className="text-violet-400 font-semibold">{file.name}</span> : <><span className="font-semibold text-slate-300">Click to upload</span> or drag and drop</>}
                </p>
                <p className="text-xs text-slate-500">PDF, TXT, MD, PPTX, Audio</p>
              </div>
              <input
                id="modal-file-upload"
                type="file"
                className="hidden"
                onChange={e => setFile(e.target.files ? e.target.files[0] : null)}
                accept=".txt,.md,.pdf,.pptx,.ppt,.png,.jpg,.jpeg,.mp3,.wav,.ogg,.aac"
              />
            </label>
          </div>
        )}

        <Button type="submit" isLoading={isSubmitting} className="w-full bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500" disabled={isSubmitting || (noteType === 'file' && !file) || (noteType === 'text' && !content)}>
          {isSubmitting ? 'Adding...' : (noteType === 'file' ? 'Upload File' : 'Save Note')}
        </Button>
      </form>
    </Modal>
  );
};

// --- FlashcardsView Sub-Component ---
const FlashcardsView: React.FC<{
  flashcards: FlashcardType[],
  onGenerateFromNotes: () => void,
  onGenerateFromFile: (file: File | null) => void,
  isGenerating: boolean,
  isFileGenerating: boolean,
  courseId: string,
  onUpdateCard: (card: FlashcardType, correct: boolean) => void
}> = ({
  flashcards, onGenerateFromNotes, onGenerateFromFile, isGenerating, isFileGenerating, courseId, onUpdateCard
}) => {
    const [reviewFlashcards, setReviewFlashcards] = useState<FlashcardType[]>([]);
    const [isReviewing, setIsReviewing] = useState(false);
    const fileInputRef = useRef<HTMLInputElement>(null); // Ref for hidden file input

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      const file = event.target.files?.[0];
      if (file) {
        onGenerateFromFile(file);
      }
      // Reset file input to allow uploading the same file again
      if (event.target) {
        event.target.value = '';
      }
    };

    const startReview = () => {
      const now = Date.now();
      const oneDay = 24 * 60 * 60 * 1000;
      const reviewable = flashcards.filter(f => {
        if (!f.lastReview || !f.bucket) return true;
        const daysSinceReview = (now - f.lastReview) / oneDay;
        if (f.bucket === 1) return daysSinceReview >= 1;
        if (f.bucket === 2) return daysSinceReview >= 3;
        if (f.bucket === 3) return daysSinceReview >= 7;
        if (f.bucket === 4) return daysSinceReview >= 14;
        return daysSinceReview >= 30;
      });
      setReviewFlashcards(reviewable);
      setIsReviewing(true);
    };


    return (
      <div className="p-6 overflow-y-auto">
        {/* Hidden file input */}
        <input
          type="file"
          id="flashcard-file-upload"
          name="flashcardFile"
          ref={fileInputRef}
          onChange={handleFileChange}
          style={{ display: 'none' }}
          accept=".txt,.md,.pdf,.pptx,.ppt,.png,.jpg,.jpeg"
        />

        <div className="flex gap-4 mb-6">
          {/* Button to generate from existing notes */}
          <Button onClick={onGenerateFromNotes} disabled={isGenerating || isFileGenerating} isLoading={isGenerating}>
            Generate from All Notes
          </Button>
          {/* Button to trigger file upload and generation */}
          <Button
            onClick={() => fileInputRef.current?.click()}
            disabled={isGenerating || isFileGenerating}
            isLoading={isFileGenerating}
            variant="secondary" // Use a different style maybe
          >
            <Upload size={16} className="mr-2" /> Generate from File
          </Button>
          {/* Review button */}
          <Button onClick={startReview} variant="outline" disabled={flashcards.length === 0 || isGenerating || isFileGenerating}>
            Review Due Cards
          </Button>
        </div>

        <h3 className="text-lg font-bold text-slate-200 mb-4">All Flashcards ({flashcards.length})</h3>
        {flashcards.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {flashcards.map((card) => (
              <Flashcard key={card.id} front={card.front} back={card.back} />
            ))}
          </div>
        ) : (
          <p className="text-slate-400">No flashcards generated yet. Use the buttons above to create some!</p>
        )}

        {isReviewing && (
          <FlashcardPlayer
            flashcards={reviewFlashcards}
            onComplete={() => setIsReviewing(false)}
            onUpdateCard={onUpdateCard}
          />
        )}
      </div>
    );
  };

// --- FlashcardPlayer Sub-Component ---
const FlashcardPlayer: React.FC<{ flashcards: FlashcardType[], onComplete: () => void, onUpdateCard: (card: FlashcardType, correct: boolean) => void }> = ({ flashcards, onComplete, onUpdateCard }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  const handleNext = (correct: boolean) => {
    onUpdateCard(flashcards[currentIndex], correct);
    if (currentIndex < flashcards.length - 1) {
      setCurrentIndex(currentIndex + 1);
      setIsFlipped(false);
    } else {
      onComplete(); // Close after the last card
    }
  };


  if (flashcards.length === 0) {
    return (
      <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 animate-in fade-in-50" onClick={onComplete}>
        <div className="bg-slate-800 p-8 rounded-lg text-center" onClick={e => e.stopPropagation()}>
          <p className="text-xl text-white">No flashcards are due for review today!</p>
          <p className="text-slate-400 mb-6">Check back later or review all cards from the main page.</p>
          <Button onClick={onComplete} className="mt-4">Close</Button>
        </div>
      </div>
    )
  }

  const card = flashcards[currentIndex];

  return (
    <div className="fixed inset-0 bg-black/80 flex flex-col items-center justify-center z-50 animate-in fade-in-50">
      <button onClick={onComplete} className="absolute top-6 right-6 text-slate-400 hover:text-white transition-colors">
        <X size={24} />
      </button>
      <div
        className="relative w-full max-w-2xl h-80"
        style={{ perspective: '1000px' }}
      >
        <div
          className={`relative w-full h-full transition-transform duration-500 transform-style-3d ${isFlipped ? 'rotate-y-180' : ''}`}
        >
          {/* Front */}
          <div className="absolute w-full h-full bg-slate-700 rounded-lg flex items-center justify-center p-8 text-center backface-hidden">
            <p className="text-2xl text-white">{card.front}</p>
          </div>
          {/* Back */}
          <div className="absolute w-full h-full bg-sky-600 rounded-lg flex items-center justify-center p-8 text-center rotate-y-180 backface-hidden">
            <p className="text-2xl text-white">{card.back}</p>
          </div>
        </div>
      </div>

      <p className="text-slate-300 mt-4 text-sm">Card {currentIndex + 1} of {flashcards.length}</p>

      <div className="absolute bottom-10 flex gap-4">
        {!isFlipped ? (
          <Button onClick={() => setIsFlipped(true)} className="px-10 py-3 text-lg">Flip</Button>
        ) : (
          <>
            <Button onClick={() => handleNext(false)} className="bg-red-600 hover:bg-red-700 px-8 py-3 text-lg">Incorrect</Button>
            <Button onClick={() => handleNext(true)} className="bg-green-600 hover:bg-green-700 px-8 py-3 text-lg">Correct</Button>
          </>
        )}
      </div>
    </div>
  )
}

const QuizView: React.FC<{
  quizzes: PersonalQuiz[];
  onGenerateQuiz: () => void;
  isGenerating: boolean;
  onUpdateScore: (id: string, score: number) => void;
}> = ({ quizzes, onGenerateQuiz, isGenerating, onUpdateScore }) => {
  const [activeQuiz, setActiveQuiz] = useState<PersonalQuiz | null>(null);

  return (
    <div className="p-6 overflow-y-auto">
      <div className="flex gap-4 mb-6">
        <Button onClick={onGenerateQuiz} disabled={isGenerating} isLoading={isGenerating}>
          <Brain size={16} className="mr-2" /> Generate Quiz from Notes
        </Button>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {quizzes.length === 0 ? (
          <p className="text-slate-400 text-center py-10">No quizzes yet. Generate one to test your knowledge!</p>
        ) : (
          quizzes.map((quiz, idx) => (
            <div key={quiz.id || idx} className="bg-slate-800 p-4 rounded-lg flex justify-between items-center ring-1 ring-slate-700">
              <div>
                <h4 className="font-bold text-slate-200">Quiz #{quizzes.length - idx}</h4>
                <p className="text-sm text-slate-400">{new Date(quiz.dateTaken || Date.now()).toLocaleDateString()}</p>
                {quiz.completed && <p className={`text-sm font-semibold mt-1 ${quiz.score! >= 80 ? 'text-emerald-400' : 'text-amber-400'}`}>Score: {quiz.score}%</p>}
              </div>
              <Button onClick={() => setActiveQuiz(quiz)} variant="outline">
                {quiz.completed ? 'Review' : 'Start Quiz'}
              </Button>
            </div>
          ))
        )}
      </div>

      {activeQuiz && (
        <PersonalQuizPlayer
          quiz={activeQuiz}
          onClose={() => setActiveQuiz(null)}
          onComplete={(score) => {
            onUpdateScore(activeQuiz.id!, score);
            setActiveQuiz(null);
          }}
        />
      )}
    </div>
  );
};

const PersonalQuizPlayer: React.FC<{ quiz: PersonalQuiz, onClose: () => void, onComplete: (score: number) => void }> = ({ quiz, onClose, onComplete }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState<number[]>(new Array(quiz.questions.length).fill(-1));
  const [showResults, setShowResults] = useState(quiz.completed || false);

  const handleAnswer = (optionIdx: number) => {
    if (showResults) return;
    const newAnswers = [...answers];
    newAnswers[currentIndex] = optionIdx;
    setAnswers(newAnswers);
  };

  const handleSubmit = () => {
    let correct = 0;
    answers.forEach((ans, idx) => {
      if (ans === quiz.questions[idx].correctOptionIndex) correct++;
    });
    const score = Math.round((correct / quiz.questions.length) * 100);
    onComplete(score);
    setShowResults(true); // Technically component unmounts on complete, but just in case
  };

  const currentQ = quiz.questions[currentIndex];
  const isLast = currentIndex === quiz.questions.length - 1;

  return (
    <div className="fixed inset-0 bg-black/90 flex items-center justify-center z-50 animate-in fade-in-50">
      <div className="bg-slate-800 rounded-2xl w-full max-w-3xl p-8 shadow-2xl ring-1 ring-slate-700 relative">
        <button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-white"><X size={24} /></button>

        <div className="mb-6 flex justify-between items-center">
          <h3 className="text-xl font-bold text-white">Question {currentIndex + 1} of {quiz.questions.length}</h3>
          <div className="bg-slate-900 rounded-full px-3 py-1 text-sm text-slate-400">{currentQ.topic}</div>
        </div>

        <p className="text-lg text-slate-200 mb-8">{currentQ.question}</p>

        <div className="grid gap-3 mb-8">
          {currentQ.options.map((opt, idx) => {
            const isSelected = answers[currentIndex] === idx;
            const isCorrect = currentQ.correctOptionIndex === idx;

            let className = "p-4 rounded-xl text-left border-2 transition-all ";
            if (showResults) {
              if (isCorrect) className += "bg-emerald-900/30 border-emerald-500 text-emerald-100";
              else if (isSelected && !isCorrect) className += "bg-red-900/30 border-red-500 text-red-100";
              else className += "bg-slate-700 border-transparent opacity-50";
            } else {
              if (isSelected) className += "bg-violet-600/20 border-violet-500 text-violet-100";
              else className += "bg-slate-700 border-transparent hover:bg-slate-600 text-slate-200";
            }

            return (
              <button
                key={idx}
                onClick={() => handleAnswer(idx)}
                disabled={showResults}
                className={className}
              >
                {opt}
              </button>
            )
          })}
        </div>

        <div className="flex justify-between">
          <Button onClick={() => setCurrentIndex(prev => Math.max(0, prev - 1))} disabled={currentIndex === 0} variant="secondary">Previous</Button>
          {isLast ? (
            !showResults && <Button onClick={handleSubmit} className="bg-emerald-600 hover:bg-emerald-500" disabled={answers.includes(-1)}>Submit Quiz</Button>
          ) : (
            <Button onClick={() => setCurrentIndex(prev => prev + 1)}>Next</Button>
          )}
        </div>
      </div>
    </div>
  );
};

export default Notes;